[package]
name = "keechain-core"
version.workspace = true
edition = "2021"
description = "KeeChain Core library."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
keywords.workspace = true
rust-version.workspace = true

[features]
default = ["sysinfo"]
nostr = ["dep:nostr"]

[dependencies]
aes = "0.8"
base64 = "0.21"
bdk = { version = "0.28", default-features = false, features = ["std"] }
bip39 = "2.0"
bitcoin = { version = "0.29", default-features = false, features = ["rand", "serde"] }
cbc = { version = "0.1", features = ["alloc"] }
nostr = { version = "=0.22.0-bitcoin-v0.29", default-features = false, features = ["nip06", "nip19"], optional = true }
once_cell = "1.17"
rand_chacha = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[target.'cfg(not(target_vendor = "apple"))'.dependencies]
sysinfo = { version = "0.29", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
bdk = { version = "0.28", default-features = false, features = ["async-interface", "std"] }
getrandom = { version = "0.2", features = ["js"] }