[workspace]
members = [
    "keechain",
    "keechain-cli",
    "keechain-common",
    "keechain-core",
    "keechain-ffi",
]
default-members = ["keechain", "keechain-cli"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
