[package]
name = "keechain"
version.workspace = true
edition = "2021"
description.workspace = true
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "../README.md"
keywords.workspace = true
categories = ["gui"]
rust-version.workspace = true

[features]
default = []
nostr = ["keechain-core/nostr"]

[dependencies]
iced = { version = "0.6", default-features = false, features = ["image", "glow"] }
keechain-core = { version = "0.1", path = "../keechain-core" }
rfd = "0.10.0"
