[package]
name = "keechain"
version = "0.1.0"
edition = "2021"
description = "Bitcoin PSBT signer, descriptor exporter and more for offline devices."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage = "https://github.com/yukibtc/keechain"
repository = "https://github.com/yukibtc/keechain.git"
license = "MIT"
readme = "README.md"
keywords = ["bitcoin", "signer", "psbt", "offline", "cli"]
categories = ["command-line-utilities", "GUI"]
rust-version = "1.65.0"

[features]
default = []
gui = ["dep:keechain-gui"]
nostr = ["keechain-core/nostr", "keechain-gui?/nostr"]

[dependencies]
clap = { version = "4.0.27", features = ["derive"] }
console = "0.15.2"
dialoguer = "0.10.2"
env_logger = "0.9.0"
keechain-core = { path = "../keechain-core" }
keechain-gui = { path = "../keechain-gui", optional = true }
